# Generated by Django 5.0.3 on 2024-04-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_activationkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationkey',
            name='key',
            field=models.CharField(default='5d363848ea3f403a8889e87ba0e1cbd8', max_length=32),
        ),
    ]
