# Generated by Django 5.0.4 on 2024-04-10 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_activationkey_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationkey',
            name='key',
            field=models.CharField(default='c6354a93cb9643ad9b6ef789cf8efe6f', max_length=32),
        ),
    ]
