# Generated by Django 5.0.4 on 2024-04-10 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_activationkey_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationkey',
            name='key',
            field=models.CharField(default='bde67ddb30e84c379765219edf08baec', max_length=32),
        ),
    ]
