# Generated by Django 5.0.4 on 2024-04-10 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_activationkey_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationkey',
            name='key',
            field=models.CharField(default='56d74bc05bb64886bc3f3612ecc4f174', max_length=32),
        ),
    ]
