# Generated by Django 5.0.4 on 2024-04-10 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_activationkey_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationkey',
            name='key',
            field=models.CharField(default='6cf3bd9b21aa4b4e96a1907b0c6dee4a', max_length=32),
        ),
    ]
