# Generated by Django 5.0.4 on 2024-04-10 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_activationkey_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationkey',
            name='key',
            field=models.CharField(default='ebaeaaad0c2e403ca57a35dfb0ee0fe4', max_length=32),
        ),
    ]
