# Generated by Django 5.0.3 on 2024-04-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('currency', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('Failed', 'Failed'), ('Success', 'Success'), ('Pending', 'Pending'), ('Under Process', 'Under Process'), ('Deleted', 'Deleted')], default='Pending', max_length=20)),
            ],
        ),
    ]
