# Generated by Django 5.0.4 on 2024-04-10 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_created_at_payment_updated_at_and_more'),
        ('projects', '0002_project_deleted_at_project_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='project',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectrelated', to='projects.project'),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accountrelated', to=settings.AUTH_USER_MODEL),
        ),
    ]
