# Generated by Django 5.0.4 on 2024-04-10 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_project_payment_user'),
        ('projects', '0002_project_deleted_at_project_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='project',
            field=models.OneToOneField(default='null', on_delete=django.db.models.deletion.CASCADE, related_name='projectrelated', to='projects.project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Failed', 'Failed'), ('Success', 'Success'), ('Pending', 'Pending'), ('Under Process', 'Under Process'), ('Deleted', 'Deleted')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.OneToOneField(default='null', on_delete=django.db.models.deletion.CASCADE, related_name='accountrelated', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
